"use strict";

const mix                 = require('mixwith').mix;
const WatermoonEnemy      = require('@app/content/enemies/watermoon').WatermoonEnemy;
const WatermoonReputation = require('@mixins/enemy/reputation/watermoon').WatermoonReputation;
const FuriousAction       = require('@mixins/enemy/actions/furious').FuriousAction;
const DrainLifeAction     = require('@mixins/enemy/actions/drain_life').DrainLifeAction;
const CrippleAction       = require('@mixins/enemy/actions/cripple').CrippleAction;
const DropsMoondrop       = require('@mixins/enemy/loot/moondrop').DropsMoondrop;
const Loot                = require('@app/loot').Loot;
const LootSlot            = require('@app/loot').LootSlot;

const FLAGS = require('@constants').FLAGS;

const FLAG_BOSS_STATS = 'boss_stats';

class DeathBossEnemy extends mix(WatermoonEnemy).with(
  FuriousAction(10),
  DrainLifeAction(20),
  CrippleAction(20),
  DropsMoondrop(100, 8),
  WatermoonReputation(75)
) {
  constructor() {
    super({
      type: 'watermoon-mystic-death-boss',
      displayName: 'Grand Lich',
      description: "Floating a full foot off the ground and cloaked in rich red robes with a large hood pulled well forward, this spectral abomination is evil magic incarnate.  Liches must sacrifice the thing they value the most in order to gain their unholy magic, and what is left is completely lacking in positive human qualities.",
      isBoss: true,
      stats: {
        base: {
          maxHp: 75,
          force: 7,
          goldMin: 50,
          goldMax: 50
        },
        perLevel: {
          maxHp: 35,
          force: 1,
          goldMin: 20,
          goldMax: 25
        }
      },
      fightActions: {
        summonZombies: 5,
      },
      loot: new Loot(
        new LootSlot().addEntry(100, 'quest-watermoon-death_soul_gem')
      )
    });
  }

  /**
   * Summon a group of zombies that deal only 50% attack and have 10% of health of boss.
   * After they die, bring back the boss.
   *
   * @param {Character} character - The opposing character.
   *
   * @return {array} Messages generated by these actions.
   */
  summonZombies(character) {
    const Enemies = require('@app/content/enemies').Enemies;
    let zombies = Enemies.new('watermoon-mystic-death-zombie_protectors');
    zombies.setLevel(this.level);
    zombies.hp = zombies.maxHp;
    zombies.setFlag(FLAG_BOSS_STATS, {
      hp: this.hp,
      flags: this._flags,
    });

    character.enemy = zombies;

    return [__(":fearful: The Grand Lich laughs and falls back, while a horde of Zombie Protectors rise from the ground and attack!")];
  }

  /**
   * Character has beat the mini-boss.
   *
   * @param {Character} character - The character who won the fight.
   * @param {array} messages - Any messages that have happened so far in combat.
   *
   * @return {array}
   */
  doFightSuccess(character, messages) {
    // Define in here to prevent circular references
    const Locations = require('@app/content/locations').Locations;

    const steps = character.getFlag('steps_death');
    character.clearFlag('steps_death');
    character.track('Grand Lich Defeated', { steps });

    character.setFlag(FLAGS.DEATH_BOSS_DEFEATED);
    character.location = Locations.new("watermoon-mystic-mausoleum");
    messages.push(__("With the Grand Lich defeated, the Death Plane fades around you and the Death Portal spirals closed."));

    return messages;
  }
}

module.exports = DeathBossEnemy;