"use strict";

const mix        = require('mixwith').mix;
const Consumable = require('@app/content/items/consumable').Consumable;
const ScaleCost  = require('@mixins/item/scale_cost').ScaleCost;

const CHARACTER_STATE = require('@constants').CHARACTER_STATE;
const FLAGS           = require('@constants').FLAGS;

class AmbrosiaConsumable extends mix(Consumable).with(ScaleCost(1)) {
  constructor() {
    super({
      type: 'consumables-ambrosia',
      displayName: __('Ambrosia'),
      description: __('This delicate blue bottle contains a viscous liquid inside that will heal and restore all your HP and MP.',),
    });
  }

  /**
   * If this consumable item can actually be used right now.
   *
   * @param Character character the character to check.
   *
   * @return boolean
   */
  canBeUsed(character) {
    return character.hp < character.maxHp || character.mp < character.maxMp;
  }

  /**
   * Consume the ambrosia, fully heal & restore the character.
   *
   * @param Character character The character to heal.
   *
   * @return string The message generated by consuming this item.
   */
  consume(character) {
    if (character.state === CHARACTER_STATE.FIGHTING) {
      if (character.hasFlag(FLAGS.AMBROSIA_FIGHT_USE)) {
        return [__(":warning: You can only use 1 Ambrosia per fight.")];
      }

      character.setFlag(FLAGS.AMBROSIA_FIGHT_USE, 1);
    }

    super.consume(character);

    let text = [];

    const healed = character.increaseHp(character.maxHp);
    if (healed) {
      text.push(__("heal %d HP", healed));
    }

    const restored = character.increaseMp(character.maxMp);
    if (restored) {
      text.push(__("restore %d MP", restored));
    }

    return [__(":yum: You uncork the bottle and imbibe the honey-like liquid inside.  You %s.", text.join(" and "))];
  }

  /**
   * Get a description of how this item will change the provided character's stats.
   *
   * @param Character character The character to evaluate against.
   *
   * @return string
   */
  getShopDescription(character) {
    return __("Recover all your HP and MP (once per fight).");
  }
}

module.exports = AmbrosiaConsumable;