"use strict";

const Consumable = require('@app/content/items/consumable').Consumable;

const FLAGS = require('@constants').FLAGS;

class AntidoteConsumable extends Consumable {
  constructor() {
    super({
      type: 'consumables-antidote',
      displayName: __('Antidote'),
      description: __('A handful of crushed herbs in a small sachet.'),
      gold: 10,
    });
  }

  /**
   * If this consumable item can actually be used right now.
   *
   * @param Character character the character to check.
   *
   * @return boolean
   */
  canBeUsed(character) {
    return character.hasFlag(FLAGS.POISONED_TURNS);
  }

  /**
   * Consume the antidote, cancel the poison.
   *
   * @param Character character The character to remove poison from.
   *
   * @return string The message generated by consuming this item.
   */
  consume(character) {
    super.consume(character);

    character.clearFlag(FLAGS.POISONED_TURNS);
    character.clearFlag(FLAGS.POISON_DAMAGE);

    return [__(':yum: The antidote leaves a bitter yet comforting taste in your mouth as you feel it cleanse your body of poisons.')];
  }

  /**
   * Get a description of how this item will change the provided character's stats.
   *
   * @param Character character The character to evaluate against.
   *
   * @return string
   */
  getShopDescription(character) {
    return __('Remove poison.');
  }
}

module.exports = AntidoteConsumable;