"use strict";

const Consumable = require('@app/content/items/consumable').Consumable;

const FLAGS = require('@constants').FLAGS;

const DURATION = 6;
const HEAL_HP = 50;

class HotChocolateConsumable extends Consumable {
  constructor() {
    super({
      type: 'consumables-hot_chocolate',
      displayName: __("Hot Chocolate"),
      description: __("A small thermos, filled with a shot of magically-warmed hot chocolate."),
      gold: 5,
    });
  }

  /**
   * If this consumable item can actually be used right now.
   *
   * @param Character character the character to check.
   *
   * @return boolean
   */
  canBeUsed(character) {
    return character.hasFlag(FLAGS.CHILLED_TURNS);
  }

  /**
   * Consume the smelling salts, cancel the daze.
   *
   * @param Character character The character to remove poison from.
   *
   * @return string The message generated by consuming this item.
   */
  consume(character) {
    super.consume(character);

    character.clearFlag(FLAGS.CHILLED_TURNS);
    character.setFlag(FLAGS.HOT_CHOCOLATE_TURNS, DURATION);
    const difference = character.increaseHp(HEAL_HP);

    return [__(":coffee:  You gently sip your Hot Chocolate and feel warmth course through your veins.  You recover *%d* HP.", difference)];
  }

  /**
   * Get a description of how this item will change the provided character's stats.
   *
   * @param Character character The character to evaluate against.
   *
   * @return string
   */
  getShopDescription(character) {
    return __('Removes and prevents chill for %d turns and heals %d HP.', DURATION, HEAL_HP);
  }
}

module.exports = HotChocolateConsumable;