"use strict";

const Consumable = require('@app/content/items/consumable').Consumable;

const FLAGS = require('@constants').FLAGS;

class SmellingSaltsConsumable extends Consumable {
  constructor() {
    super({
      type: 'consumables-smelling_salts',
      displayName: __('Smelling Salts'),
      description: __('A small amount of ammonia salts suspended in alcohol.  It smells terrible, but that\'s kind of the point!'),
      gold: 5,
    });
  }

  /**
   * If this consumable item can actually be used right now.
   *
   * @param Character character the character to check.
   *
   * @return boolean
   */
  canBeUsed(character) {
    return character.hasFlag(FLAGS.DAZED_TURNS);
  }

  /**
   * Consume the smelling salts, cancel the daze.
   *
   * @param Character character The character to remove poison from.
   *
   * @return string The message generated by consuming this item.
   */
  consume(character) {
    super.consume(character);

    character.clearFlag(FLAGS.DAZED_TURNS);

    return [__(':yum: You take a deep breath of the smelling salts and your head clears.  Your defence returns to normal!')];
  }

  /**
   * Get a description of how this item will change the provided character's stats.
   *
   * @param Character character The character to evaluate against.
   *
   * @return string
   */
  getShopDescription(character) {
    return __('Remove daze.');
  }
}

module.exports = SmellingSaltsConsumable;