"use strict";

const Accessory = require('@app/content/items/equipment/accessories');

class GarnetHeartAmuletAccessory extends Accessory {
  constructor() {
    super({
      type: 'equipment-accessories-015_garnet_heart_amulet',
      displayName: __('Garnet Heart Amulet'),
      description: __('A heart-shaped amulet made from a purple garnet stone.'),
      level: 15,
      gold: 150,
    });
  }

  /**
   * Get a description of how this item will change the provided character's stats.
   *
   * @param {Character} character - The character to evaluate against.
   *
   * @return {string}
   */
  getShopDescription(character) {
    return __("Regenerate 3 HP per round.");
  }

  /**
   * Do any actions that might happen after each round of combat (regen, etc.)
   *
   * @param {Character} character - The character in combat.
   *
   * @return {array} The messages generated by these actions.
   */
  doPostRoundActions(character) {
    // Can't do anything for dead characters.
    if (character.hp <= 0) {
      return [];
    }

    const hp = character.increaseHp(3);
    return [__(":purple_heart: Your %s regenerates %d HP.", this.getDisplayName(character), hp)];
  }
}

module.exports = GarnetHeartAmuletAccessory;